apiVersion: v1
kind: Service
metadata:
  name: "{{ include "spark-harness.fullname" . }}-worker"
  labels:
{{ include "spark-harness.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "spark-harness.name" . }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
