{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stub-recsys.serviceAccountName" . }}
  labels:
{{ include "stub-recsys.labels" . | indent 4 }}
{{- end -}}
