apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: recsys-locust-harness
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: harness.{{ .Values.hostAddress }}
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: stub-stub-recsys
              servicePort: 8080
    - host: pprox1.{{ .Values.hostAddress }}
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: stub-proxy-sgx-1
              servicePort: 8080
    - host: pprox2.{{ .Values.hostAddress }}
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: stub-proxy-sgx-2
              servicePort: 8080

