dependencies:
  - name: mongodb
    version: 5.16.4
    repository: https://charts.helm.sh/stable
    alias: mongo
  - name: elasticsearch
    version: 7.1.1
    repository: https://helm.elastic.co
    alias: elastic
