# remove labels
kubectl label node nuc3.maas tier-
kubectl label node nuc4.maas tier-
kubectl label node nuc5.maas tier-
kubectl label node nuc6.maas tier-
kubectl label node nuc7.maas tier-
kubectl label node nuc8.maas tier-
kubectl label node nuc9.maas tier-
kubectl label node nuc10.maas tier-
kubectl label node nuc11.maas tier-
kubectl label node nuc12.maas tier-
kubectl label node nuc13.maas tier-
kubectl label node nuc14.maas tier-
kubectl label node nuc15.maas tier-
kubectl label node nuc16.maas tier-
kubectl label node nuc17.maas tier-
kubectl label node nuc18.maas tier-
kubectl label node nuc22.maas tier-
kubectl label node nuc23.maas tier-
kubectl label node nuc24.maas tier-
kubectl label node nuc31.maas tier-
kubectl label node nuc34.maas tier-
kubectl label node nuc35.maas tier-

# label nodes
kubectl label node nuc3.maas tier=manager
kubectl label node nuc4.maas tier=harness
kubectl label node nuc5.maas tier=harness
kubectl label node nuc6.maas tier=harness
kubectl label node nuc7.maas tier=harness
kubectl label node nuc8.maas tier=harness
kubectl label node nuc9.maas tier=harness
kubectl label node nuc10.maas tier=harness
kubectl label node nuc11.maas tier=mongo
kubectl label node nuc12.maas tier=harness
kubectl label node nuc13.maas tier=pprox
kubectl label node nuc14.maas tier=pprox
kubectl label node nuc15.maas tier=pprox
kubectl label node nuc16.maas tier=pprox
kubectl label node nuc17.maas tier=elastic
kubectl label node nuc18.maas tier=elastic
kubectl label node nuc22.maas tier=elastic
kubectl label node nuc23.maas tier=efk
kubectl label node nuc24.maas tier=elastic
kubectl label node nuc31.maas tier=elastic
kubectl label node nuc34.maas tier=injector
kubectl label node nuc35.maas tier=injector
