apiVersion: v1
kind: Service
metadata:
  name: {{ include "injector.fullname" . }}-master
  labels:
{{ include "injector.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5557
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: {{ include "injector.name" . }}-master
    app.kubernetes.io/instance: {{ .Release.Name }}
