apiVersion: v1
kind: Service
metadata:
  name: "recsys-harness-0"
  labels:
{{ include "harness.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "harness.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    statefulset.kubernetes.io/pod-name: "recsys-harness-0"